#!/usr/bin/env python3
"""
Quick setup script for Sports Analytics Platform with real live data.
Handles environment setup and initial configuration.

Run: python setup.py
"""
import os
import sys
from pathlib import Path


def setup():
    """Interactive setup wizard."""
    print("\n" + "="*70)
    print("⚽  SPORTS ANALYTICS PLATFORM - SETUP WIZARD")
    print("="*70)
    
    # Check Python version
    if sys.version_info < (3, 9):
        print("❌ Python 3.9+ required")
        sys.exit(1)
    
    # Get API key
    print("\n📍 Step 1: Football-Data.org API Key")
    print("-" * 70)
    print("You need a FREE API key to fetch real match data.")
    print("Get it from: https://www.football-data.org/")
    print()
    api_key = input("Paste your API key: ").strip()
    
    if not api_key or len(api_key) < 20:
        print("❌ Invalid API key")
        sys.exit(1)
    
    # Get active leagues
    print("\n📍 Step 2: Select Leagues")
    print("-" * 70)
    print("Available leagues:")
    print("  PL   = Premier League (England)")
    print("  SA   = Serie A (Italy)")
    print("  DL   = Bundesliga (Germany)")
    print("  FL1  = Ligue 1 (France)")
    print("  PPL  = Primeira Liga (Portugal)")
    print("  EC   = European Championship")
    print("  CL   = Champions League")
    print()
    leagues_input = input("Enter leagues (comma-separated) [PL,SA,DL,FL1,PPL]: ").strip()
    leagues = leagues_input if leagues_input else "PL,SA,DL,FL1,PPL"
    
    # Create .env file
    print("\n📍 Step 3: Creating .env file")
    print("-" * 70)
    
    backend_dir = Path("backend")
    env_file = backend_dir / ".env"
    
    env_content = f"""# Sports Analytics Platform Configuration
# Generated by setup.py

# Application
APP_NAME="Sports Analytics Platform"
DEBUG=True

# Database (SQLite for dev, PostgreSQL for prod)
DATABASE_URL="sqlite+aiosqlite:///./sports.db"

# Redis (leave empty for in-memory pub/sub)
REDIS_URL=""

# Data Source: "live" (real API) or "simulator" (demo)
DATA_SOURCE="live"

# Football-Data.org API Configuration
FOOTBALL_DATA_API_KEY="{api_key}"
FOOTBALL_DATA_BASE_URL="https://api.football-data.org/v4"

# Active Leagues
ACTIVE_LEAGUES="{leagues}"

# Polling intervals (seconds)
LIVE_FEED_POLL_SECONDS=30
SIMULATOR_TICK_SECONDS=10

# ML & Artifacts
ARTIFACTS_DIR="ml/artifacts"

# CORS
CORS_ORIGINS="http://localhost:5173,http://localhost:3000"

# Monitoring
ENABLE_METRICS=True
"""
    
    with open(env_file, "w") as f:
        f.write(env_content)
    
    print(f"✅ Created {env_file}")
    
    # Summary
    print("\n" + "="*70)
    print("✅ SETUP COMPLETE!")
    print("="*70)
    print("\nNext steps:")
    print("\n1. Install backend dependencies:")
    print("   cd backend")
    print("   python -m venv venv")
    print("   venv\\Scripts\\activate  (Windows) or source venv/bin/activate (Mac/Linux)")
    print("   pip install -r requirements.txt")
    print("\n2. Install frontend dependencies:")
    print("   cd frontend")
    print("   npm install")
    print("\n3. Train ML model (optional, but recommended):")
    print("   cd backend")
    print("   python -m ml.train --csv backend/ml/sample_data.csv --trials 20")
    print("\n4. Start backend server:")
    print("   cd backend")
    print("   python -m uvicorn app.main:app --reload")
    print("\n5. In another terminal, start frontend:")
    print("   cd frontend")
    print("   npm run dev")
    print("\n6. Open browser:")
    print("   http://localhost:5173")
    print("\n7. View API docs:")
    print("   http://localhost:8000/docs")
    print("\n" + "="*70)
    print("For detailed instructions, see SETUP_GUIDE.md")
    print("="*70 + "\n")


if __name__ == "__main__":
    try:
        setup()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
